TOP_DIR = .

include Makefile.defaults

all: lib

lib:
	$(MAKE) -C lib

test: lib
	$(MAKE) -C bin

clean:
	$(MAKE) -C lib clean
	$(MAKE) -C bin clean

help:
	@$(ECHO) "Targets:\nlib\tbuild static and shared libraries\ntest\trun the unit tests\nclean\tremove files generated by build"

.PHONY: all lib test clean help